docs_dir: doc/book
site_dir: doc/html
nav:
    - index.md
    - Overview: overview.md
    - Installation: install.md
    - Usage: usage.md
    - Reference:
        - "Custom Responses": custom-responses.md
        - "Emitting Responses": emitting-responses.md
        - Serialization: serialization.md
        - API: api.md
site_name: laminas-diactoros
site_description: 'laminas-diactoros: PSR-7 HTTP message implementation'
repo_url: 'https://github.com/laminas/laminas-diactoros'
